exports.seed = function(knex) {
	// Deletes ALL existing entries
	return knex('student')
		.del()
		.then(function() {
			// Inserts seed entries
			return knex('student').insert([
				{
					cpr: '1',
					first_name: 'Mariam',
					additional_names: 'Saleh Isa',
					gender: 'F',
					home_telephone: '12345678',
					mobile_telephone: '12345678',
					email: 'fakeemail@gmail.com',
					preferred_contact_type_id: 1,
					birthdate: new Date(2003, 4, 23),
					school_name: 'Alduraz',
					school_grade_id: 1,
					location_id: 1,
					block_code: 363,
					road: '2550',
					building: '298',
					flat: '12',
					primary_emergency_contact_name: 'Mohammad Saleh',
					primary_emergency_relationship: 'Father',
					primary_emergency_phone: '12345678',
					emergency_contact_name: 'Fatwa Saleh Isa',
					emergency_relationship: 'Sister',
					emergency_phone: '12345678',
					notes: 'This student is just alright',
					no_call: true,
					delinquent: false,
					expelled: true,
					family_id: 1
				},
				{
					cpr: '2',
					first_name: 'Hamad',
					additional_names: 'Saleh Isa',
					gender: 'M',
					home_telephone: '12345678',
					mobile_telephone: '12345678',
					email: 'fakeemail@gmail.com',
					preferred_contact_type_id: 1,
					birthdate: new Date(2003, 4, 23),
					school_name: 'Alduraz',
					school_grade_id: 1,
					location_id: 1,
					block_code: 363,
					road: '2550',
					building: '298',
					flat: '12',
					primary_emergency_contact_name: 'Mohammad Saleh',
					primary_emergency_relationship: 'Father',
					primary_emergency_phone: '12345678',
					emergency_contact_name: 'Fatwa Saleh Isa',
					emergency_relationship: 'Sister',
					emergency_phone: '12345678',
					notes: 'This student is just alright',
					no_call: true,
					delinquent: false,
					expelled: true,
					family_id: 2
				},
				{
					cpr: '3',
					first_name: 'Fatima',
					additional_names: 'Saleh Isa',
					gender: 'F',
					home_telephone: '12345678',
					mobile_telephone: '12345678',
					email: 'fakeemail@gmail.com',
					preferred_contact_type_id: 1,
					birthdate: new Date(2003, 4, 23),
					school_name: 'Alduraz',
					school_grade_id: 1,
					location_id: 1,
					block_code: 363,
					road: '2550',
					building: '298',
					flat: '12',
					primary_emergency_contact_name: 'Mohammad Saleh',
					primary_emergency_relationship: 'Father',
					primary_emergency_phone: '12345678',
					emergency_contact_name: 'Fatwa Saleh Isa',
					emergency_relationship: 'Sister',
					emergency_phone: '12345678',
					notes: 'This student is just alright',
					no_call: true,
					delinquent: false,
					expelled: true,
					family_id: 3
				},
				{
					cpr: '4',
					first_name: 'Hassan',
					additional_names: 'Saleh Isa',
					gender: 'M',
					home_telephone: '12345678',
					mobile_telephone: '12345678',
					email: 'fakeemail@gmail.com',
					preferred_contact_type_id: 1,
					birthdate: new Date(2003, 4, 23),
					school_name: 'Alduraz',
					school_grade_id: 1,
					location_id: 1,
					block_code: 363,
					road: '2550',
					building: '298',
					flat: '12',
					primary_emergency_contact_name: 'Mohammad Saleh',
					primary_emergency_relationship: 'Father',
					primary_emergency_phone: '12345678',
					emergency_contact_name: 'Fatwa Saleh Isa',
					emergency_relationship: 'Sister',
					emergency_phone: '12345678',
					notes: 'This student is just alright',
					no_call: true,
					delinquent: false,
					expelled: true,
					family_id: 4
				},
				{
					cpr: '5',
					first_name: 'Layla',
					additional_names: 'Saleh Isa',
					gender: 'F',
					home_telephone: '12345678',
					mobile_telephone: '12345678',
					email: 'fakeemail@gmail.com',
					preferred_contact_type_id: 1,
					birthdate: new Date(2003, 4, 23),
					school_name: 'Alduraz',
					school_grade_id: 1,
					location_id: 1,
					block_code: 363,
					road: '2550',
					building: '298',
					flat: '12',
					primary_emergency_contact_name: 'Mohammad Saleh',
					primary_emergency_relationship: 'Father',
					primary_emergency_phone: '12345678',
					emergency_contact_name: 'Fatwa Saleh Isa',
					emergency_relationship: 'Sister',
					emergency_phone: '12345678',
					notes: 'This student is just alright',
					no_call: true,
					delinquent: false,
					expelled: true,
					family_id: 5
				},
				{
					cpr: '6',
					first_name: 'Hiba',
					additional_names: 'Saleh Isa',
					gender: 'F',
					home_telephone: '12345678',
					mobile_telephone: '12345678',
					email: 'fakeemail@gmail.com',
					preferred_contact_type_id: 1,
					birthdate: new Date(2003, 4, 23),
					school_name: 'Alduraz',
					school_grade_id: 1,
					location_id: 1,
					block_code: 363,
					road: '2550',
					building: '298',
					flat: '12',
					primary_emergency_contact_name: 'Mohammad Saleh',
					primary_emergency_relationship: 'Father',
					primary_emergency_phone: '12345678',
					emergency_contact_name: 'Fatwa Saleh Isa',
					emergency_relationship: 'Sister',
					emergency_phone: '12345678',
					notes: 'This student is just alright',
					no_call: true,
					delinquent: false,
					expelled: true,
					family_id: 6
				}
			]);
		});
};
