exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('student')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('student').insert([
        {
          cpr: '1',
          first_name: 'Mariam',
          additional_names: 'Saleh Isa',
          gender: 'F',
          birthdate:new Date(2003,4,23),
          school_grade_id: 1,
          school_name: 'Alduraz',
          home_telephone: '12345678',
          mobile_telephone: '12345678',
          block_code: 363,
          road: '2550',
          building: '298',
          flat: '12',
          email: 'fakeemail@gmail.com',
          notes: 'This student is just alright',
          preferred_contact_type_id: 1,
          no_call: true,
          delinquent: false,
          expelled: true,
          location_id: 1,
          family_id: 1
        },
        {
          cpr: '2',
          first_name: 'Hamad',
          additional_names: 'Saleh Isa',
          gender: 'M',
          birthdate:new Date(2003,4,23),
          school_grade_id: 1,
          school_name: 'Alduraz',
          home_telephone: '12345678',
          mobile_telephone: '12345678',
          block_code: 363,
          road: '2550',
          building: '298',
          flat: '12',
          email: 'fakeemail@gmail.com',
          notes: 'This student is just alright',
          preferred_contact_type_id: 1,
          no_call: true,
          delinquent: false,
          expelled: true,
          location_id: 1,
          family_id: 1
        },
        {
          cpr: '3',
          first_name: 'Fatima',
          additional_names: 'Saleh Isa',
          gender: 'F',
          birthdate:new Date(2003,4,23),
          school_grade_id: 1,
          school_name: 'Alduraz',
          home_telephone: '12345678',
          mobile_telephone: '12345678',
          block_code: 363,
          road: '2550',
          building: '298',
          flat: '12',
          email: 'fakeemail@gmail.com',
          notes: 'This student is just alright',
          preferred_contact_type_id: 1,
          no_call: true,
          delinquent: false,
          expelled: true,
          location_id: 1,
          family_id: 2
        },
        {
          cpr: '4',
          first_name: 'Hassan',
          additional_names: 'Saleh Isa',
          gender: 'M',
          birthdate:new Date(2003,4,23),
          school_grade_id: 1,
          school_name: 'Alduraz',
          home_telephone: '12345678',
          mobile_telephone: '12345678',
          block_code: 363,
          road: '2550',
          building: '298',
          flat: '12',
          email: 'fakeemail@gmail.com',
          notes: 'This student is just alright',
          preferred_contact_type_id: 1,
          no_call: true,
          delinquent: false,
          expelled: true,
          location_id: 1,
          family_id: 3
        },
        {
          cpr: '5',
          first_name: 'Layla',
          additional_names: 'Saleh Isa',
          gender: 'F',
          birthdate:new Date(2003,4,23),
          school_grade_id: 1,
          school_name: 'Alduraz',
          home_telephone: '12345678',
          mobile_telephone: '12345678',
          block_code: 363,
          road: '2550',
          building: '298',
          flat: '12',
          email: 'fakeemail@gmail.com',
          notes: 'This student is just alright',
          preferred_contact_type_id: 1,
          no_call: true,
          delinquent: false,
          expelled: true,
          location_id: 1,
          family_id: 4
        },
        {
          cpr: '6',
          first_name: 'Hiba',
          additional_names: 'Saleh Isa',
          gender: 'F',
          birthdate:new Date(2003,4,23),
          school_grade_id: 1,
          school_name: 'Alduraz',
          home_telephone: '12345678',
          mobile_telephone: '12345678',
          block_code: 363,
          road: '2550',
          building: '298',
          flat: '12',
          email: 'fakeemail@gmail.com',
          notes: 'This student is just alright',
          preferred_contact_type_id: 1,
          no_call: true,
          delinquent: false,
          expelled: true,
          location_id: 1,
          family_id: 5
        }
      ]);
    });
};
